### PR TITLE
microverse portfolio mobile first project

### PR DESCRIPTION
**Pull request by clin2on3mun**
using HTML and CSS 
1. using HTML semantics divide a page into two sections.
2. using CSS flex-box to align items on the webpage
3. using linters to remove errors and put codes to standard (for reviews)

### CODE REVIEW

**Review by bobb-Rob — COMMENTED** [review]
Hi @clin2on3mun , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that linters checks are not running. Please add the correct linter files in your root folder and re-submit.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by clin2on3mun** [comment]
hey Robertson Arthur, 
Thank you for reviewing my codes and providing encouraging feedback I made changes the wrong directory was created so the linters were not active on the pull request

**Review by ha-manel — COMMENTED** [review]
# STATUS: INVALID 🔴 
Hi @clin2on3mun 
I'm sure you put a lot of effort into this project but this PR is invalid because linters are not running 😓

I understand that you have setup linters in the `main` branch but not in this one, however you should create branches based on the main one so you can have all the necessary files in each branch 👍 
to fix the issue you can just merge main to your feature branch or add the files in main to the feature branch 👍  

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by clin2on3mun** [comment]
Hi @ha-manel,
thank you for reviewing my code I am getting trying to get better at GitHub and your feedback helped me a lot.

**Review by NduatiKagiri — COMMENTED** [review]
Hi @clin2on3mun , 

# INVALID REVIEW REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have Linters set up and running, and does not have all the required project files.
Please always make sure that you create your feature branches from `main`, and never push changes directly to `main`.
Since you have not yet received any review and your next request will be a first review, you can create a new branch from the main branch, add all the required files and open a new Pull Request. This will help you not to waste a lot of time as you are new to using GitHub. But since this will go against Microverse guidelines, make sure that in your next review request, you add the link to this Pull Request in the 'additional information' part, and explain to the next reviewer why you opened a new PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request closed without merging**
